name: aws-oidc-test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assume AWS role via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::797273591655:role/GitHubDeployRole
          role-session-name: gha-${{ github.run_id }}
          aws-region: us-east-2

      - name: Who am I in AWS?
        run: aws sts get-caller-identity

      - name: Can I use the permission I was granted?
        run: aws s3 ls
